Repository itislu/42-Rush-ft_shmup, pull requests merged in 2025-06, with the labels that each got.

#1 fix: Fix gcc compilation by not sharing the same name between types and variables
  src/Background.cpp
  src/Background.hpp
  src/Coordinate.hpp
  src/Game.cpp
  src/Player.cpp
  src/game.hpp
  src/main.cpp
Labels: bug

#2 fix: Stop time when gameover
  src/game.hpp
  src/main.cpp
Labels: bug

#3 docs: Add README
  README.md
Labels: documentation

#4 fix: to windows to null after deleting, and check for null before deleting
  src/main.cpp
Labels: bug

#5 feat: Added minimum terminal size
  src/game.hpp
  src/main.cpp
Labels: enhancement

#7 feat: Adjusted enemy cooldowns, enemies spawn in 3 waves each having a different type and dont move in synchronization
  src/main.cpp
Labels: enhancement

#8 Change Boss behavior and appearance, menu is now bold, added invis frame flash
  src/Player.cpp
  src/game.hpp
  src/main.cpp
Labels: enhancement

#10 build: Fix macOS compilation issue caused by ncursesw
  Makefile
  build/config.mk
Labels: bug

#11 feat: Add restart option (`R` key) when gameover
  README.md
  src/Player.cpp
  src/game.hpp
  src/main.cpp
Labels: enhancement

#13 feat: gain 1 hp per player after killing boss, boss movement gets adjusted based on window height, new bullet type for boss, added auto fire toggle
  README.md
  src/Player.cpp
  src/game.hpp
  src/main.cpp
Labels: enhancement

#17 fix: Stop time during pause
  src/game.hpp
  src/main.cpp
Labels: bug
